#   This file is part of Desktop-D30
#   Copyright (C) 2026 Chris Griffin (bearded-griffin)
# 
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation version 3 of the License.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Makefile wrapper for CMake

# Detect Operating System
ifeq ($(OS),Windows_NT)
    DETECTED_OS := Windows
    SHELL_RM := rmdir /s /q
    SHELL_MKDIR := mkdir
    EXE_EXT := .exe
    GENERATOR := "MinGW Makefiles"
else
    DETECTED_OS := $(shell uname -s)
    SHELL_RM := rm -rf
    SHELL_MKDIR := mkdir -p
    EXE_EXT :=
    GENERATOR := Ninja
endif

# Default build type
TYPE ?= Debug

# Standard CMake build folder
BUILD_DIR = build

.PHONY: all build clean run re run_tests coverage clean-coverage windows

# Default target: build the project
all: build

# Configure CMake
configure:
	cmake -S . -B $(BUILD_DIR) -G $(GENERATOR) -DCMAKE_BUILD_TYPE=$(TYPE)

# Compile the project
build: configure
	cmake --build $(BUILD_DIR) --config $(TYPE)

# Specific Windows build (can be called from Linux if cross-compiling toolchain is set, 
# or directly on Windows)
windows:
	cmake -S . -B build_win -DCMAKE_BUILD_TYPE=Release
	cmake --build build_win --config Release

# Build a release version
release:
	./build_release.sh

# Run the executable
run: build
	./$(BUILD_DIR)/Desktop-D30$(EXE_EXT)

# Run all tests
run_tests: build
	./$(BUILD_DIR)/tests/run_tests$(EXE_EXT)

# Nuke the build folder
clean:
	$(SHELL_RM) $(BUILD_DIR)
	$(SHELL_RM) build_win

# "Re-make": Clean and then build
re: clean build

# Coverage Report Generation
COVERAGE_DIR = coverage_report

coverage: clean-coverage clean build run_tests
	@echo "Collecting coverage data..."
	mkdir -p $(COVERAGE_DIR)
	lcov --capture --directory $(BUILD_DIR) \
	     --output-file $(COVERAGE_DIR)/coverage.info \
	     --ignore-errors mismatch \
	     --exclude "$(BUILD_DIR)/_deps/*" \
	     --exclude "/usr/*"
	@echo "Generating HTML report..."
	genhtml $(COVERAGE_DIR)/coverage.info --output-directory $(COVERAGE_DIR)
	@echo "Coverage report generated in $(COVERAGE_DIR)"
	@# Attempt to open the report in the default browser (platform-dependent)
	@if command -v xdg-open > /dev/null; then xdg-open $(COVERAGE_DIR)/index.html; \
	elif command -v open > /dev/null; then open $(COVERAGE_DIR)/index.html; \
	else echo "Could not open report automatically. Please open $(COVERAGE_DIR)/index.html manually."; fi

clean-coverage:
	@echo "Cleaning previous coverage data..."
	-rm -rf $(COVERAGE_DIR)
	@# Remove all .gcda files (coverage data) generated by tests
	-find $(BUILD_DIR) -name "*.gcda" -delete