#   This file is part of Desktop-D30
#   Copyright (C) 2026 Chris Griffin (bearded-griffin)
# 
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation version 3 of the License.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Makefile wrapper for CMake

# Default build type
TYPE ?= Debug

# Standard CMake build folder
BUILD_DIR = build

.PHONY: all build clean run re run_tests coverage clean-coverage

# Default target: build the project
all: build

# Configure CMake (Using Ninja)
configure:
	cmake -S . -B $(BUILD_DIR) -G Ninja -DCMAKE_BUILD_TYPE=$(TYPE)

# Compile the project
build:
	@if [ ! -d "$(BUILD_DIR)" ]; then $(MAKE) configure; fi
	cmake --build $(BUILD_DIR)

# Build a release version
release:
	./build_release.sh

# Run the executable
run: build
	./$(BUILD_DIR)/Desktop-D30

# Run all tests
run_tests: build
	./$(BUILD_DIR)/tests/run_tests

# Nuke the build folder
clean:
	rm -rf $(BUILD_DIR)

# "Re-make": Clean and then build
re: clean build

# Coverage Report Generation
COVERAGE_DIR = coverage_report

coverage: clean-coverage clean build run_tests
	@echo "Collecting coverage data..."
	mkdir -p $(COVERAGE_DIR)
	lcov --capture --directory $(BUILD_DIR) \
	     --output-file $(COVERAGE_DIR)/coverage.info \
	     --ignore-errors mismatch \
	     --exclude "$(BUILD_DIR)/_deps/*" \
	     --exclude "/usr/*"
	@echo "Generating HTML report..."
	genhtml $(COVERAGE_DIR)/coverage.info --output-directory $(COVERAGE_DIR)
	@echo "Coverage report generated in $(COVERAGE_DIR)"
	@# Attempt to open the report in the default browser (platform-dependent)
	@if command -v xdg-open > /dev/null; then xdg-open $(COVERAGE_DIR)/index.html; \
	elif command -v open > /dev/null; then open $(COVERAGE_DIR)/index.html; \
	else echo "Could not open report automatically. Please open $(COVERAGE_DIR)/index.html manually."; fi

clean-coverage:
	@echo "Cleaning previous coverage data..."
	-rm -rf $(COVERAGE_DIR)
	@# Remove all .gcda files (coverage data) generated by tests
	-find $(BUILD_DIR) -name "*.gcda" -delete