site_name: Desktop-D30 Documentation
theme:
  name: material
  palette:
    primary: sky blue
    accent: indigo

nav:
  - Welcome: index.md
  - Installation: installation.md
  - The Interface: interface.md
  - Managing Assets: assets.md
  - Bluetooth Printing: printing.md
  - Batch Printing: batch-printing.md
  - Shortcuts: shortcuts.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
